/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-23 09:39:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class bg_002dleft_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  <script Language=\"JavaScript\">\r\n");
      out.write(" function quit() {\r\n");
      out.write("  if(confirm(\"确定要退出后台吗？\")){\r\n");
      out.write("    window.location.href=\"loginOut.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("  }\r\n");
      out.write(" </script>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");
com.wy.domain.ManagerForm manager=(com.wy.domain.ManagerForm)session.getAttribute("manager"); 
      out.write("\r\n");
      out.write("<table width=\"35\" height=\"22\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><img src=\"image/bg_left01.jpg\" width=\"170\" height=\"45\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("      <table width=\"170\" height=\"46\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_left02.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><table width=\"118\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"118\" height=\"17\" align=\"center\" valign=\"bottom\"><div align=\"left\"><a href=\"goodsAction.do?action=0\" class=\"a3\">商品设置</a></div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"17\" align=\"center\"><div align=\"left\"><font color=\"#FFFFFF\">Goods Manage</font></div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"170\" height=\"46\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_left02.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><table width=\"118\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"109\" height=\"17\" align=\"center\" valign=\"bottom\"><div align=\"left\"><a href=\"memberAction.do?action=2\" class=\"a3\">会员设置</a></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"17\" align=\"center\"><div align=\"left\"><font color=\"#FFFFFF\">Member Manage</font></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("          </table></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      \r\n");
      out.write("      ");
if(manager.getSigh()==1){
      out.write("        \r\n");
      out.write("      <table width=\"170\" height=\"46\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_left02.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><div align=\"left\">\r\n");
      out.write("            <table width=\"118\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=\"127\" height=\"17\" align=\"center\" valign=\"bottom\"><div align=\"left\"><a href=\"managerAction.do?action=1\" class=\"a3\">后台管理员设置</a></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td height=\"17\" align=\"center\"><div align=\"left\"><font color=\"#FFFFFF\">Admin Manage</font></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("             </table>\r\n");
      out.write("          </div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      ");
}else{
      out.write("\r\n");
      out.write("       <table width=\"170\" height=\"46\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_left02.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><div align=\"left\">\r\n");
      out.write("            <table width=\"118\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=\"127\" height=\"17\" align=\"center\" valign=\"bottom\"><div align=\"left\"><a href=\"bg-managerUpdatePassword.jsp\" class=\"a3\">修改密码</a></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td height=\"17\" align=\"center\"><div align=\"left\"><font color=\"#FFFFFF\">Amend Password</font></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("             </table>\r\n");
      out.write("          </div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>      \r\n");
      out.write("      ");
}
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <table width=\"170\" height=\"46\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_left02.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><table width=\"118\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"127\" height=\"17\" align=\"center\" valign=\"bottom\"><div align=\"left\"><a href=\"orderAction.do?action=0\" class=\"a3\">订单设置</a></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"17\" align=\"center\"><div align=\"left\"><font color=\"#FFFFFF\">Order Manage</font></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("          </table></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"170\" height=\"46\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_left02.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><table width=\"118\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"127\" height=\"17\" align=\"center\" valign=\"bottom\"><div align=\"left\"><a href=\"afficheAction.do?action=0\" class=\"a3\">公告设置</a></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"17\" align=\"center\"><div align=\"left\"><font color=\"#FFFFFF\">Placard Manage</font></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("          </table></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"170\" height=\"46\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_left02.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><table width=\"118\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"127\" height=\"17\" align=\"center\" valign=\"bottom\"><div align=\"left\"><a href=\"linkAction.do?action=0\" class=\"a3\">友情设置</a></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"17\" align=\"center\"><div align=\"left\"><font color=\"#FFFFFF\">Link Manage</font></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("          </table></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"170\" height=\"47\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_left03.jpg\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><table width=\"118\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"127\" height=\"17\" align=\"center\" valign=\"bottom\"><div align=\"left\"><a href=\"javascript:quit()\" class=\"a3\">安全退出</a></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"17\" align=\"center\"><div align=\"left\"><font color=\"#FFFFFF\">Exit Background</font></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("          </table></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"37\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("          <td><img src=\"image/bg_left04.jpg\" width=\"170\" height=\"100\"></td>\r\n");
      out.write("        </tr>     \r\n");
      out.write("      </table>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
