/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-23 09:39:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.wy.domain.ManagerForm;

public final class bg_002dup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      com.wy.tool.CountTime countTime = null;
      countTime = (com.wy.tool.CountTime) _jspx_page_context.getAttribute("countTime", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (countTime == null){
        countTime = new com.wy.tool.CountTime();
        _jspx_page_context.setAttribute("countTime", countTime, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

if(session.getAttribute("manager")==null){
out.print("<script language=javascript>alert('您已经与服务器断开连接，请重新登录！');window.location.href='bg-land.jsp';</script>");
}else{
ManagerForm manager=(ManagerForm)session.getAttribute("manager");

      out.write("\r\n");
      out.write("<table width=\"788\" height=\"66\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_01.jpg\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"top\"><table width=\"770\" border=\"0\" align=\"center\">\r\n");
      out.write("      <tr >\r\n");
      out.write("        <td width=\"413\" height=\"53\" valign=\"bottom\"><div align=\"right\"></div></td>\r\n");
      out.write("        <td width=\"347\" valign=\"bottom\" align=\"right\"><font color=\"#FFFFFF\"><a href=\"goodsAction.do?action=0\" class=\"a2\">商品查询</a> | <a href=\"bigTypeAction.do?action=0\" class=\"a2\">大类别查询</a> | <a href=\"smallTypeAction.do?action=0\" class=\"a2\">小类别查询</a> | <a href=\"orderAction.do?action=0\" class=\"a2\">返回首页</a></font></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table width=\"788\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#000000\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"15\" height=\"25\">&nbsp;</td>\r\n");
      out.write("    <td width=\"579\"><font color=\"#FFFFFF\">当前登录：");
      out.print(manager.getAccount());
      out.write("</font></td>\r\n");
      out.write("    <td width=\"194\"><font color=\"#FFFFFF\">今天是");
      out.print(countTime.currentlyTime());
      out.write("</font></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
