/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-23 09:39:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import com.wy.domain.AfficheForm;

public final class bg_002dafficheContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
AfficheForm affiche=(AfficheForm)request.getAttribute("affiche");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function checkEmpty(form){\r\n");
      out.write("for(i=0;i<form.length;i++){\r\n");
      out.write("if(form.elements[i].value==\"\"){\r\n");
      out.write("alert(\"表单信息不能为空\");\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>网上购物的后台</title>\r\n");
      out.write("</head>\r\n");
      out.write(" <link href=\"css/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bg-up.jsp", out, true);
      out.write("\r\n");
      out.write("<table width=\"788\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"170\"  valign=\"top\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bg-left.jsp", out, true);
      out.write("</td>\r\n");
      out.write("    <td width=\"618\" align=\"center\" valign=\"top\" bgcolor=\"#FFFFFF\"> <br>\r\n");
      out.write("\t\r\n");
      out.write("        <table width=\"610\" height=\"25\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/bg_02.jpg\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><div align=\"center\"><strong>查看公告信息</strong></div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("        <table width=\"90%\" height=\"243\"  border=\"1\" cellpadding=\"1\" cellspacing=\"1\" bordercolor=\"#FFFFFF\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"23%\" height=\"30\"><div align=\"center\">公告标题</div></td>\r\n");
      out.write("            <td width=\"77%\" bgcolor=\"#FFFFFF\">&nbsp;");
      out.print(affiche.getName());
      out.write("</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td width=\"23%\" height=\"208\"><div align=\"center\">公告内容</div></td>\r\n");
      out.write("            <td width=\"77%\" bgcolor=\"#FFFFFF\">&nbsp;");
      out.print(affiche.getContent());
      out.write("</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    \r\n");
      out.write("\t    <table width=\"82%\" height=\"30\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>&nbsp;</td>\r\n");
      out.write("            <td><div align=\"right\"><a href=\"javascript:history.go(-1)\">返回</a></div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bg-down.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
